### ISSUE TITLE
Statements in last paragraph of README are not true any more

### ISSUE THREAD

**Issue by helhum** [bnf/typo3ctl#1]
https://github.com/bnf/typo3ctl#further-notes

Replacement has been [removed](https://github.com/TYPO3-Console/TYPO3-Console/commit/5616ad1c8baffb3c1fe06394013812c9a714f8f4) and that state is released with 5.5.5

**Comment by bnf** [comment]
Thanks for that!
Removed that in https://github.com/bnf/typo3ctl/commit/1570ebb3da0912c87b04d7f71d6020233d75d3b7
